name: Trends Cron

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: {}

jobs:
  hit-cron-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call trends cron endpoint
        run: |
          curl -fsSL "${{ secrets.CRON_URL }}"

